LEARNING_RATE = 0.1
MAX_EPISODES = 10000
LEARNING_PERIOD = MAX_EPISODES // 10
EVAL_PERIOD = LEARNING_PERIOD // 2
START_EPSILON = 0.04
EPSILON_DECAY = START_EPSILON / (MAX_EPISODES / 2)
FINAL_TEMPERATURE = 0.1
DISCOUNT = 0.9